export const styles = `
.dn{max-width:850px;margin:0 auto;padding:24px 20px 48px;font:14px/1.55 system-ui,sans-serif;color:inherit}
.dn *{box-sizing:border-box}.dn h2{font-size:28px;letter-spacing:-.8px;margin:3px 0}.dn h3{font-size:17px;margin:30px 0 8px}.dn p{margin:7px 0 14px}
.dn-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.dn-kicker{font-size:11px;font-weight:750;letter-spacing:2px;color:#0d9488;margin:0!important}.dn-badge{font-size:11px;white-space:nowrap;padding:5px 10px;border:1px solid #0d948866;border-radius:20px;color:#0d9488}
.dn fieldset{border:1px solid #8884;border-radius:12px;padding:20px;margin:18px 0}.dn legend{padding:0 8px;font-weight:650;font-size:16px}.dn label{display:flex;gap:8px;align-items:center}.dn input[type=checkbox]{accent-color:#0d9488;width:15px;height:15px;flex-shrink:0}
.dn-row{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.dn-muted{opacity:.66;font-size:12px}.dn-field{align-items:stretch!important;flex-direction:column;margin:10px 0}.dn input[type=url],.dn input[type=password]{width:100%;padding:10px 12px;border:1px solid #8885;border-radius:7px;font:inherit;background:transparent;color:inherit}
.dn-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.dn button{border:1px solid #8885;border-radius:7px;padding:8px 13px;background:transparent;color:inherit;font:inherit;font-size:12px;font-weight:600;cursor:pointer}.dn button:hover{background:#8881}.dn button:disabled{opacity:.4;cursor:default}.dn .dn-primary{background:#0f766e;color:white;border-color:#0f766e}.dn .dn-primary:hover{background:#115e59}.dn :focus-visible{outline:2px solid #0d9488;outline-offset:3px}
.dn-events{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:20px 0;padding-top:16px;border-top:1px solid #8883}.dn-message:empty{display:none}.dn-message{padding:10px 14px;background:#0d948815;border-radius:8px;margin-top:15px}.dn-error{color:#dc6b54;font-size:12px}.dn-empty{padding:24px;text-align:center;border:1px dashed #8885;border-radius:8px;opacity:.65}
.dn-table{overflow-x:auto}.dn table{width:100%;border-collapse:collapse;font-size:12px;text-align:left}.dn th{font-weight:500;opacity:.6}.dn th,.dn td{padding:12px 9px;border-bottom:1px solid #8883;vertical-align:top}.dn td:first-child{max-width:290px;overflow-wrap:anywhere}.dn td strong{font-weight:600}
@media(max-width:560px){.dn{padding:16px 8px}.dn-events{grid-template-columns:1fr}.dn-heading{display:block}.dn-badge{display:inline-block;margin:8px 0}.dn fieldset{padding:14px}}
`;
